version: '3.7'
services:

  cloud-db:
    container_name: cloud-db
    image: mysql:latest
    networks:
      - cloud-network

    environment:
      - MYSQL_USER=cloudPeople
      - MYSQL_PASSWORD=soCloudPass
      - MYSQL_DATABASE=diploma_cloud
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  server-app:
    container_name: cloud-app-spring-by-sobin
    build: ./
    networks:
      - cloud-network
    depends_on:
      - cloud-db
    environment:
      - MYSQL_HOST=cloud-db
      - MYSQL_USERNAME=cloudPeople
      - MYSQL_PASSWORD=soCloudPass
      - MYSQL_DATABASE=diploma_cloud
      - MYSQL_PORT=3306
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    #    environment:
    #      SPRING_LIQUIBASE_URL: jdbc:mysql://database:3306/diploma_cloud
    #      SPRING_LIQUIBASE_USER: root
    #      SPRING_LIQUIBASE_PASSWORD: mysql
    ports:
      - "8085:8085"

  client:
    container_name: frontend-client
    build:
      context: netology-diplom-frontend
      dockerfile: Dockerfile
    image: cloud-storage-front:latest
    networks:
      - cloud-network
#    environment:
#      - HOST_NAME=192.168.99.100
#      - HOST_PORT=8085
    ports:
      - "8080:8080"


networks:
  cloud-network:
    name: cloud-network

volumes:
  dbvol:

